name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    # TODO: add toolchains and let it fail on nightly
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo 
    - name: Run tests
      run: cargo test --verbose
